### ISSUE TITLE
Lerner Lab Conversion Progress

### ISSUE THREAD

**Issue by pauladkisson** [catalystneuro/lerner-lab-to-nwb#13]
# Lerner Lab Conversion Progress

![Progress](https://progress-bar.dev/100/) 🎉

### Behavior
- [x] Develop Medpc reader and behavior interface: #1
- [x] Add support for alternative medpc file structure (by date instead of by animal): #6 
- [x] Convert all FP Behavior Sessions: #3
- [x] Add missing MSNs: #14 
- [x] Add `from_csv` option to behavior interface #11
- [x] Add medpc reader to neuroconv: https://github.com/catalystneuro/neuroconv/pull/883

### Photometry
- [x] Develop FiberPhotometry Interface AND convert all photometry sessions: #9
- [x] Update ndx-photometry to support latest hdmf: https://github.com/catalystneuro/ndx-photometry/pull/7
- [x] Make general improvements to ndx-photometry for better data representation: https://github.com/catalystneuro/ndx-photometry/pull/14
- [x] Follow-up on fiber photometry conversion to implement feedback from lerner lab on edge cases: #18 
- [x] Switch to ndx-fiber-photometry: #24 
- [x] Develop TDT photometry interface for neuroconv: https://github.com/catalystneuro/neuroconv/pull/920

### Behavior
- [x] Convert all Opto Behavior Sessions: #8

### Optogenetics
- [x] Develop Optogenetic Interface AND convert all optogenetic sessions: #8
- [x] Follow-up on optogenetic conversion to implement feedback from Lerner Lab on edge cases: #19 
- [x] move `create_stimulation_timeseries()` to neuroconv: https://github.com/catalystneuro/neuroconv/pull/832 and #28 
## Miscellaneous
- [x] Extract subject metadata from sheets: #20 
- [x] Western Blot: #23 
- [x] Upload my version of the Gdrive dataset with fixes (ex. FP Experiments/Behavior/PS/332.393/332.393)
- [x] Set up Dandiset: https://dandiarchive.org/dandiset/000971
- [x] Add convert_all_sessions.py to cookiecutter: https://github.com/catalystneuro/cookiecutter-my-lab-to-nwb-template/pull/23
- [x] Update Readme.md: #34
- [x] Add example notebook to dandi example notebooks: https://github.com/dandi/example-notebooks/pull/91
- [x] Final Fixes: #35
